Custom Clothing Addition
FWolfe/Zomboid-Modding-Guide pull request #4
Opened 2021-01-09 08:57 UTC by AuthenticPeach

I wrote up a guide for adding custom clothing. I will need help on making the model from scratch. I cover everything after that particular step. 
-Peach

2021-01-09 19:32 UTC, yooksi requested changes
@AuthenticPeach Thanks for the submission! 

I cannot speak about the content itself because I am not familiar with clothes modding, but in addition to the comments I've provided on individual lines here are the following things that can be done to improve your pull request as per Git standards:

- Git commit names (f94f409 and b5c468e) need to be worded in [imperative-form](https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches?id=HEAD#n133).
  > Describe your changes in imperative mood, e.g. "make xyzzy do frotz" instead of "[This patch] makes xyzzy do frotz" or "[I] changed xyzzy to do frotz", as if you are giving orders to the codebase to change its behavior. 
- Commit b5c468e should be excluded from this PR and submitted in another one as it has nothing to do with custom clothing. This way it can be reviewed separately.

Please take this review as suggestions rather then demands. They are meant to as helpful *improvements* to the guide, not rigidly defined contribution rules.

2021-01-09 19:32 UTC, yooksi commented on customclothing/Custom-Clothing.md
> +}
Script blocks could be marked as `properties` code blocks to enable [syntax highlighting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting).
This of course improves readability, but keep in mind that white spaces are not allowed in keys and values.

```properties
  imports {
      Base
  }
    item Jacket_Grimes                  ### ClothingItem name
    {
        Type = Clothing,
        DisplayName = Ricks_Jacket,     ### This is the name that appears in the inventory menu in-game. 
        ClothingItem = Jacket_Grimes,   ### This is the name of the XML clothing item that you need to refer to correctly. 
        BodyLocation = Jacket,          ### This is connected with Bodylocations.lua which controls the restrictions on what combinations of clothing that your character can wear.
        Icon = JacketRick,              ### Inventory icon for the jacket. The sprite is named item_JacketRick in the textures folder in the mod directory.
        BloodLocation = Jacket,
        RunSpeedModifier = 0.93,
        CombatSpeedModifier = 0.98,
        BiteDefense = 20,
        ScratchDefense = 30,
        NeckProtectionModifier = 0.5,
        Insulation = 0.7,
        WindResistance = 0.7,
        FabricType = Cotton,
        WaterResistance = 0.5,
        Weight = 2,
    }
}
```

2021-01-09 19:32 UTC, yooksi commented on customclothing/Custom-Clothing.md
> +```
As already mentioned this code block would benefit from syntax highlighting:

```xml
<?xml version="1.0" encoding="utf-8"?>
<clothingItem>
	<m_MaleModel>skinned\clothes\bob_jacket</m_MaleModel>     ### The 3d models with animations
	<m_FemaleModel>skinned\clothes\kate_jacket</m_FemaleModel> ### The 3d models with animations
	<m_GUID>6c247231-dbe5-45cd-8e93-78d4ef716ff9</m_GUID> ### A unique GUID for the clothingitem. See Step 3.
	<m_Static>false</m_Static>
	<m_AllowRandomHue>false</m_AllowRandomHue>    ###No Hue
	<m_AllowRandomTint>false</m_AllowRandomTint>  ###No Tint 
	<m_AttachBone></m_AttachBone>
	<m_Masks>13</m_Masks>
	<m_Masks>3</m_Masks>
	<m_Masks>5</m_Masks>
	<m_UnderlayMasksFolder>media/textures/Clothes/Jacket/Masks</m_UnderlayMasksFolder>   ###Masks that the clothingitem uses
	<textureChoices>clothes\jacket\jacket_grimes</textureChoices>                        ###The texture that the model uses
</clothingItem>
```

2021-01-09 19:32 UTC, yooksi commented on customclothing/Custom-Clothing.md
> +Go to https://www.guidgenerator.com/online-guid-generator.aspx , and copy and paste in a new GUID into its respected section. All clothingitems, models, and makeup get
Links can be enclosed and inlined like this:

> Go to [guidgenerator.com](https://www.guidgenerator.com/online-guid-generator.aspx), and...

Read more about formatting links in Markdown:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links

2021-01-09 19:32 UTC, yooksi commented on customclothing/Custom-Clothing.md
> +-EXTRA-
Comments should not be visible to readers, mark them like this:  
`[//]: # "-EXTRA"`

2021-01-09 19:32 UTC, yooksi commented on customclothing/Custom-Clothing.md
> +3 - The item will appear in inventory but appears invisible on character - this is probably because it did not get a new GUID table addition.
This list is not formatted correctly and items have collapsed.
The numbers need to be immediately followed by a single period.

For example:

1. First item.
2. Second item.
3. Third item.

Read more about formatting links in Markdown:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists

2021-01-09 19:32 UTC, yooksi commented on customclothing/Custom-Clothing.md
> +### HOW TO MAKE CUSTOM CLOTHING APPEAR ON ZOMBIES
Headers should not be written in all-caps, it creates confusion and inconsistency.

2021-01-09 19:32 UTC, yooksi commented on customclothing/Custom-Clothing.md
> +-NEED HELP ON THIS ONE -
Comments should not be visible to readers, mark them like this:  
`[//]: # "-NEED HELP ON THIS ONE-"`

2021-01-10 03:18 UTC, FWolfe commented on customclothing/Custom-Clothing.md
> +}
Should probably use proper `/** Comment **/` brackets that are actually used in the script files instead of `#` style comments.

2021-01-10 03:20 UTC, FWolfe commented on customclothing/Custom-Clothing.md
> +```
This could do with proper xml `<!-- comments -->` instead of `#`

2021-01-10 03:30 UTC, FWolfe commented
Thanks for taking the time to write this up. I'm thinking this should go in a tutorials folder & section instead of the main guide, as its mainly a "how-to" (do this, then do this etc), where the main guide should be of a more technical nature IMO

2021-01-10 04:55 UTC, yooksi commented
> This is probably unnecessary. Most proper text editors and IDE's have similar features built in that can find/replace text recursively in directories using regex, including the previously mentioned Notepad++.

Modders should be encouraged to use an IDE over Notepad++.
Here is a [mod template](https://github.com/yooksi/pz-zmod) that has a development environment setup for IntelliJ. It has run configurations setup for de-compiling and running the game from IDE. That should probably be included in the guide as well once I finish working on it.

2021-01-10 07:52 UTC, yooksi reviewed
Looks much better, I will do some more formatting before we merge it.

2021-01-10 08:52 UTC, yooksi commented
@FWolfe Let me know if you have any suggestions before we merge.

2021-01-10 11:40 UTC, AuthenticPeach reviewed
I made the recommended changes. My apologies, this is my first time using markdown.

2021-01-11 11:47 UTC, yooksi approved these changes
> I made the recommended changes. My apologies, this is my first time using markdown.

No worries, I rebased your [commits](https://github.com/FWolfe/Zomboid-Modding-Guide/pull/4/commits) so they accurately describe the changes, consolidated other commits and did some text reformatting. We are just waiting for @FWolfe to confirm that he is happy with the changes, and then we can merge.

2021-01-13 03:46 UTC, merged